### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.squey.Squey#1]
The build failed because the tarball sha256 doesn't match.

https://buildbot.flathub.org/#/builders/25/builds/5818

**Comment by jbleonesio** [comment]
Indeed the produced build slightly changed its sha256 when I tried to rebuild the software for its old package name.

I wanted to add the "end-of-life-rebase" tag to the old package name com.gitlab.inendi.Inspector (see https://github.com/flathub/com.gitlab.inendi.Inspector/pull/4/files) but I didn't succeed to build it anymore...

Is it mandatory to be able to build the old package to add the "end-of-life-rebase" tag or could I just merge the PR as is ?

By the way, I'm curious why the new package was rebuilt by flathub after it was already published ?

Thank for your help !

**Comment by hfiguiere** [comment]
> Indeed the produced build slightly changed its sha256 when I tried to rebuild the software for its old package name.

Don't do that. A releasae is a release.

> By the way, I'm curious why the new package was rebuilt by flathub after it was already published ?

Sometime things need to be rebuilt for the metadata. This is expected.

**Comment by jbleonesio** [comment]
Two releases were published since, closing issue.
